# Generated by Django 2.0.4 on 2018-04-16 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filestorage', '0002_auto_20180412_1048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('locationText', models.TextField(blank=True, default='')),
                ('locationData', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('public', models.BooleanField(default=False)),
                ('confidential', models.BooleanField(default=True)),
                ('sourceId', models.CharField(blank=True, max_length=200, null=True)),
                ('sourceURL', models.CharField(blank=True, max_length=200, null=True)),
                ('sourceURI', models.CharField(blank=True, max_length=200, null=True)),
                ('doctype', models.CharField(choices=[('PDF', 'Pdf'), ('IMG', 'Image'), ('LINK', 'Weblink'), ('VIDEO', 'Video Link'), ('AUDIO', 'Audio Link'), ('TXT', 'Text'), ('MISC', 'Misc')], default='MISC', max_length=8)),
                ('contentRaw', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('fileRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filestorage.File')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources_main.Source'),
        ),
    ]
