# Generated by Django 2.0.4 on 2018-04-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0002_auto_20180416_1056_squashed_0003_auto_20180416_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
