# Generated by Django 2.0.4 on 2018-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0003_auto_20180416_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='pageX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='pageY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='timecode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
