# Generated by Django 2.0.4 on 2018-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0004_auto_20180416_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='embedId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
