# Generated by Django 2.0.4 on 2018-05-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0007_auto_20180509_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
            preserve_default=False,
        ),
    ]
