# Generated by Django 2.0.4 on 2018-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_projecttag_tag'),
        ('sources_main', '0008_auto_20180509_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(related_name='sources', to='organisation.Tag'),
        ),
    ]
