# Generated by Django 2.0.6 on 2018-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0010_auto_20180614_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='confidential',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='posBottom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='posLeft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='posRight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='posTop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
