# Generated by Django 2.0.6 on 2018-08-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0011_auto_20180716_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='embedId',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
