# Generated by Django 2.0.6 on 2018-08-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20180815_1439'),
        ('sources_main', '0012_auto_20180812_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Collection'),
        ),
    ]
