# Generated by Django 2.0.6 on 2018-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0014_auto_20180824_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='timecode',
            new_name='timecodeFrom',
        ),
        migrations.AddField(
            model_name='annotation',
            name='timecodeTo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
