# Generated by Django 2.0.6 on 2018-09-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0015_auto_20180905_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Collection'),
        ),
        migrations.AlterField(
            model_name='source',
            name='doctype',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('IMG', 'Image'), ('LINK', 'Weblink'), ('VIDEO', 'Video Link'), ('AUDIO', 'Audio Link'), ('DATASET', 'Dataset'), ('TXT', 'Text'), ('MISC', 'Misc')], default='MISC', max_length=8),
        ),
    ]
