# Generated by Django 2.1 on 2018-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0018_migrate_sourcetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='doctype',
            field=models.CharField(choices=[('DOC', 'Document'), ('PDF', 'Pdf'), ('IMG', 'Image'), ('LINK', 'Weblink'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DATA', 'Dataset'), ('MISC', 'Misc')], default='MISC', max_length=8),
        ),
    ]
