# Generated by Django 2.1 on 2019-02-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0019_auto_20181122_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='file',
        ),
    ]
