# Generated by Django 2.1 on 2019-02-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0020_remove_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='confidential',
        ),
        migrations.RemoveField(
            model_name='source',
            name='confidential',
        ),
    ]
