# Generated by Django 2.1 on 2019-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0021_auto_20190207_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='publishedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
