# Generated by Django 2.1 on 2019-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_auto_20190211_1623'),
        ('sources_main', '0022_source_publisheddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='stories',
            field=models.ManyToManyField(related_name='sources', to='organisation.Story'),
        ),
    ]
