# Generated by Django 2.1 on 2019-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0023_source_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='sources', to='organisation.Story'),
        ),
        migrations.AlterField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sources', to='organisation.Tag'),
        ),
    ]
