# Generated by Django 2.1 on 2019-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0024_auto_20190218_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='doctype',
            new_name='sourcetype',
        ),
    ]
