# Generated by Django 2.1 on 2019-04-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0026_auto_20190326_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='sourceURI',
            new_name='externalServiceId',
        ),
    ]
