version: '3'

#
# Dossier Sources Docker Compose Setup
#

services:

  nginx:
    #
    # Hosting of static files and proxies to webservice
    #
    image: nginx
    volumes:
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/inc:/etc/nginx/inc
      - ./app/static:/files/static
      - ./dist:/files/apps
      - ./demos/blog-usage/dist:/files/embed/demo

      # Uploads
      - ./app/media:/files/media

    depends_on:
      - webapp

  webapp:
    build: app
    environment:
      # exposing config vars fron .env
      # inside the container
      SOURCES_MYSQL_HOST: ${SOURCES_MYSQL_HOST}
      SOURCES_MYSQL_USER: ${SOURCES_MYSQL_USER}
      SOURCES_MYSQL_PASSWORD: ${SOURCES_MYSQL_PASSWORD}
      SOURCES_MYSQL_PORT: ${SOURCES_MYSQL_PORT}
      SOURCES_MYSQL_DATABASE: ${SOURCES_MYSQL_DATABASE}
      SOURCES_DJANGO_SECRET_KEY: ${SOURCES_DJANGO_SECRET_KEY}
      SOURCES_DJANGO_ALLOWED_HOSTS: ${SOURCES_DJANGO_ALLOWED_HOSTS}
      SOURCES_DJANGO_DEBUG: ${SOURCES_DJANGO_DEBUG}
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - elasticsearch
      - celery
      - queue_broker
    volumes:
      # Uploads
      - ./app/media:/code/media

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./conf/mysql/custom:/etc/mysql/conf.d
      - db-volume:/var/lib/mysql
      - ./test_data/dbdump:/var/dump

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  celery:
    #
    # Celery queue for deferring pdf/document extraction
    #
    build: app
    environment:
      # exposing config vars fron .env
      # inside the container
      SOURCES_MYSQL_HOST: ${SOURCES_MYSQL_HOST}
      SOURCES_MYSQL_USER: ${SOURCES_MYSQL_USER}
      SOURCES_MYSQL_PASSWORD: ${SOURCES_MYSQL_PASSWORD}
      SOURCES_MYSQL_PORT: ${SOURCES_MYSQL_PORT}
      SOURCES_MYSQL_DATABASE: ${SOURCES_MYSQL_DATABASE}
      SOURCES_DJANGO_SECRET_KEY: ${SOURCES_DJANGO_SECRET_KEY}
      SOURCES_DJANGO_ALLOWED_HOSTS: ${SOURCES_DJANGO_ALLOWED_HOSTS}
      SOURCES_DJANGO_DEBUG: ${SOURCES_DJANGO_DEBUG}

    command: celery -A sources worker -l info
    volumes:
      # Uploads
      - ./app/media:/code/media
    depends_on:
      - db
      - queue_broker

  queue_broker:
    #
    # Backend for celery queue
    #
    image: rabbitmq:alpine

  # postfix:
  #   image: catatnight/postfix
  #   environment:
  #     - maildomain=sources-current.tt4.at
  #     - smtp_user=user:test123

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.3.3
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"

volumes:
  db-volume:
  esdata:
