# Generated by Django 2.0.3 on 2018-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
