# Generated by Django 2.1 on 2018-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0006_file_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mimetype',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
