# Generated by Django 2.1 on 2019-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0007_file_mimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloadId',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
