# Generated by Django 2.1 on 2019-02-18 15:09

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('filestorage', 'File')
    for row in MyModel.objects.all():
        row.downloadId = uuid.uuid4()
        row.save(update_fields=['downloadId'])


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0008_file_downloadid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]