# Generated by Django 2.0.6 on 2018-09-28 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources_main', '0016_auto_20180924_1823'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('source', 'user')},
        ),
    ]
