# Generated by Django 2.0.6 on 2018-07-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20180711_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafferprofile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
    ]
