# Generated by Django 2.0.6 on 2018-07-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20180712_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='users',
        ),
    ]
