# Generated by Django 2.0.6 on 2018-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_remove_organisation_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafferprofile',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stafferprofile',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
