# Generated by Django 2.0.6 on 2018-08-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources_main', '0012_auto_20180812_0753'),
        ('organisation', '0007_auto_20180716_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTag',
            new_name='Collection',
        ),
    ]
