# Generated by Django 2.1 on 2018-10-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20180815_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
