# Generated by Django 2.1 on 2019-02-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20190130_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'organisation')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'organisation')},
        ),
    ]
