# Generated by Django 2.0.6 on 2018-08-13 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcehit',
            name='referer',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcehit',
            name='remoteHost',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcehit',
            name='requestTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 13, 8, 6, 54, 267358)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcehit',
            name='userAgent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
