# Generated by Django 2.0.6 on 2018-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180813_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcehit',
            name='referer',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sourcehit',
            name='remoteHost',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sourcehit',
            name='userAgent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
