# Generated by Django 2.0.6 on 2018-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180813_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcehit',
            name='referer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcehit',
            name='remoteHost',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcehit',
            name='userAgent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
