# Generated by Django 2.1 on 2018-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180911_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcehit',
            name='eventType',
            field=models.CharField(default='', max_length=32),
        ),
    ]
