# Generated by Django 2.1 on 2019-02-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_sourcehit_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcehit',
            name='eventType',
            field=models.CharField(choices=[('load', 'load'), ('activity', 'activity')], default='load', max_length=32),
        ),
    ]
